baseurl = "austinschwartz.com:1313"
title = "purdue programming club"
theme = "vec"
languageCode = "en-us"
paginate = 10

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "post"
    weight = 0
    url = "/post"
  [[menu.main]]
    name = "contact"
    weight = 1
    url = "/contact"
  [[menu.main]]
    name = "faq"
    weight = 2
    url = "/faq"
    
[params]
  Keywords = "purdue, competitive, programming"
  Description = "Purdue Competitive Programming Club"
  Avater = "img/avatar.jpg"
  SelfIntro = "Purdue Competitive Programming Club" 
  Email = "npatwar@purdue.com"
